<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="SeoulMap.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="강서구" title="강서구" href="" coords="206,352,115,292" shape="rect">
    <area target="" alt="양천구" title="양천구" href="" coords="191,401,256,433" shape="rect">
    <area target="" alt="구로구" title="구로구" href="" coords="174,457,220,487" shape="rect">
    <area target="" alt="영등포구" title="영등포구" href="" coords="289,387,359,426" shape="rect">
    <area target="" alt="금천구" title="금천구" href="" coords="276,521,334,554" shape="rect">
    <area target="" alt="관악구" title="관악구" href="" coords="345,493,418,554" shape="rect">
    <area target="" alt="동작구" title="동작구" href="" coords="368,440,412,464" shape="rect">
    <area target="" alt="서초구" title="서초구" href="" coords="461,463,528,511" shape="rect">
    <area target="" alt="강남구" title="강남구" href="" coords="554,459,635,505" shape="rect">
    <area target="" alt="송파구" title="송파구" href="" coords="659,429,724,467" shape="rect">
    <area target="" alt="강동구" title="강동구" href="" coords="699,332,788,366" shape="rect">
    <area target="" alt="은평구" title="은평구" href="" coords="315,189,377,220" shape="rect">
    <area target="" alt="마포구" title="마포구" href="" coords="286,315,354,349" shape="rect">
    <area target="" alt="서대문구" title="서대문구" href="" coords="343,284,392,308" shape="rect">
    <area target="" alt="용산구" title="용산구" href="https://www.google.com/search?q=%EC%9A%A9%EC%82%B0%EA%B5%AC+%EC%B9%B4%ED%8E%98&amp;sca_esv=0d61033167bebd6c&amp;biw=1920&amp;bih=953&amp;tbm=lcl&amp;ei=ZgUXZ67sDq-gvr0P8N2BgQY&amp;ved=0ahUKEwiut42x8KCJAxUvkK8BHfBuIGAQ4dUDCAk&amp;uact=5&amp;oq=%EC%9A%A9%EC%82%B0%EA%B5%AC+%EC%B9%B4%ED%8E%98&amp;gs_lp=Eg1nd3Mtd2l6LWxvY2FsIhDsmqnsgrDqtawg7Lm07Y6YMgUQABiABDIGEAAYHhgPMggQABgIGB4YDzIIEAAYCBgeGA8yCBAAGAgYHhgPMggQABgIGB4YDzIIEAAYCBgeGA8yCBAAGAgYHhgPMggQABgIGB4YDzIIEAAYCBgeGA9I_hVQAFiaFHADeACQAQGYAbgBoAHzEqoBBDAuMTW4AQPIAQD4AQGYAgqgAp0JwgIIEAAYgAQYsQPCAgsQABiABBixAxiDAcICChAAGIAEGEMYigXCAgIQJsICBhAAGAgYHpgDAJIHAzMuN6AH3E0&amp;sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[37.5472408,126.98970519999999],[37.5235991,126.9603501]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9" coords="412,365,477,415" shape="rect">
    <area target="" alt="종로구" title="종로구" href="" coords="413,265,472,301" shape="rect">
    <area target="" alt="중구" title="중구" href="" coords="441,320,491,340" shape="rect">
    <area target="" alt="강북구" title="강북구" href="" coords="467,146,530,183" shape="rect">
    <area target="" alt="성북구" title="성북구" href="" coords="484,234,544,266" shape="rect">
    <area target="" alt="도봉구" title="도봉구" href="" coords="514,78,564,129" shape="rect">
    <area target="" alt="노원구" title="노원구" href="" coords="586,113,640,164" shape="rect">
    <area target="" alt="중랑구" title="중랑구" href="" coords="619,234,672,275" shape="rect">
    <area target="" alt="광진구" title="광진구" href="" coords="604,346,660,371" shape="rect">
    <area target="" alt="동대문구" title="동대문구" href="" coords="549,273,601,300" shape="rect">
    <area target="" alt="성동구" title="성동구" href="" coords="523,333,583,364" shape="rect">
</map>