--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-07-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEOUL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SEOUL" 
   (	"NAME" VARCHAR2(300 BYTE), 
	"HOTEL" VARCHAR2(300 BYTE), 
	"TICKET" VARCHAR2(300 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SEOUL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008338
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008338" ON "SYSTEM"."SEOUL" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SEOUL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SEOUL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SEOUL" MODIFY ("HOTEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SEOUL" MODIFY ("TICKET" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SEOUL" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
